### ISSUE TITLE
Which eslint-plugin-vue should be used?

### ISSUE THREAD

**Issue by skyrpex** [vuejs/eslint-config-vue#5]
There's an [eslint-plugin-vue](https://www.npmjs.com/package/eslint-plugin-vue) on NPM from @Twiknight, but there's also the one in the [VueJS Github account](https://github.com/vuejs/eslint-plugin-vue).

Is this a typo? I'm manually using the VueJS plugin by installing vuejs/eslint-plugin-vue instead of eslint-plugin-vue.

Regards,

**Comment by chrisvfritz** [comment]
We're working with Twiknight to see if we can take it over. Our plugin offers a superset of theirs, so it should be a smooth transition.

**Comment by skyrpex** [comment]
Nice to know. Will stay alert.

**Comment by Twiknight** [comment]
@chrisvfritz sure you can take over it. I'm glad the Vue team eventually decided to offer a official version.

So how can i manage it?

**Comment by chrisvfritz** [comment]
Thanks! I think something similar to [this procedure](https://github.com/slevithan/xregexp/issues/11) would be good, though the user to add would be Evan. You can see his NPM username on any official Vue library on NPM. If you have any questions/concerns, please don't hesitate to voice them. 🙂

**Comment by Twiknight** [comment]
@chrisvfritz  I'll try it this weekend. Thanks!

**Comment by Twiknight** [comment]
@chrisvfritz would you provide a ID which I should add to this project?

**Comment by chrisvfritz** [comment]
Adding Evan would be best: 

https://www.npmjs.com/~yyx990803

**Comment by Twiknight** [comment]
@chrisvfritz @yyx990803 , I've already moved the authority of eslint-plugin-vue to Evan, so would you bother to check it?

**Comment by yyx990803** [comment]
@Twiknight thanks a lot! Will take a look later.
